#!/bin/bash
procname="vin_compare"
fdpath="/home/public/xeast/run_status/vin_fd.txt"
mempath="/home/public/xeast/run_status/vin_mem.txt"
vmempath="/home/public/xeast/run_status/vin_vmem.txt"

rm -f $fdpath
rm -f $mempath
rm -f $vmempath

while true
do
	pid=$(pidof $procname)
	if [ "$pid" != "" ]	
	then
	    dateStr=`date +"%Y-%m-%d %H:%M:%S"`
   		var1=$(lsof -c $procname | wc -l)
		#var2=$(echo 0 $(awk '/Private/ {print "+", $2}' /proc/$pid/smaps) | bc )
		mem=`ps u -p $pid | tail -1`
		var2=$(echo $mem | cut -d \ -f 4)
		var3=$(nvidia-smi -q -d MEMORY | grep Used | head -1 | sed 's/.*: \([0-9]*\).*/\1/g')

		echo "$dateStr""  ""$var2" >> $mempath
		echo "$dateStr""  ""$var1" >> $fdpath
		echo "$dateStr""  ""$var3" >> $vmempath
		echo "fd-num:"$var1",mem-percent:"$var2",v-memory:"$var3
	fi
	sleep 5
done
