#!/bin/bash
procname="CheJian"
fdpath="/home/public/YongHao/RunningStatus/cjfd.txt"
mempath="/home/public/YongHao/RunningStatus/cjmem.txt"
vmempath="/home/public/YongHao/RunningStatus/cjvmem.txt"
rm -f $fdpath
rm -f $mempath
rm -f $vmempath

while true
do
	pid=$(pidof $procname)
	if [ "$pid" != "" ]	
	then
	    dateStr=`date +"%Y-%m-%d %H:%M:%S"`
   		var1=$(lsof -c $procname | wc -l)
		var2=$(echo 0 $(awk '/Private/ {print "+", $2}' /proc/$pid/smaps) | bc )
		var3=$(nvidia-smi -q -d MEMORY | grep Used | head -1 | sed 's/.*: \([0-9]*\).*/\1/g')

		echo "$dateStr""  ""$var2" >> $mempath
		echo "$dateStr""  ""$var1" >> $fdpath
		echo "$dateStr""  ""$var3" >> $vmempath
		echo "fd-num:"$var1",mem-size:"$var2",v-memory:"$var3
	fi
	sleep 15
done
